### ISSUE TITLE
Pow operator

### ISSUE THREAD

**Issue by henryiii** [borntyping/python-infix#1]
I have a request:

Addition of pow operator - it is the only python operator to have higher precesence than `*`,`/`,`%`, so it is very useful in math type contexts:
```python
>>> from uncertainties import ufloat
>>> pm = pow_infix(ufloat)
>>> print(112 **pm** 2 - 1321 **pm** 2)
-1209.0+/-2.8
```
That can be achieved with:
```python
class pow_infix(base_infix):
    def right(self, right):
        return self.func(right, self.__infix__)
    
    __pow__ = base_infix.left
    __rpow__ = right
```

Also, some of the suggestions [here](http://code.activestate.com/recipes/384122-infix-operators/) look useful. especially the bind suggestion.

Also, more default operators would be nice, as there are a large but finite number of them.

Thanks!

**Comment by borntyping** [comment]
I'll take a look at adding this when I have some time :)

**Comment by henryiii** [comment]
Thanks! If you want me to prepare a pull request, let me know. :)

I've mentioned it in my [blog](http://iscinumpy.blogspot.com/2015/07/uncertainty-extension-for-ipython.html), btw.

**Comment by borntyping** [comment]
A pull request to add those features would be fantastic :smile:
