### ISSUE TITLE
PyPi version of infix does not have make_infix

### ISSUE THREAD

**Issue by pechersky** [borntyping/python-infix#8]
Running

```
pip install --user infix
python -c 'from infix import make_infix'
```
gives an `ImportError`.

The github version does work.
```
pip install --user git+https://github.com/borntyping/python-infix
```

Could the pypi version be updated, please?

**Comment by borntyping** [comment]
Uploaded as [infix 1.2](https://pypi.python.org/pypi?name=infix&version=1.2&:action=files)

**Comment by henryiii** [comment]
Would you mind adding a git tag, too?

**Comment by borntyping** [comment]
Done!
